"use client";

import { useMemo, useState } from "react";
import {
  Download,
  FileCode,
  Presentation,
  Loader2,
  FileText,
  FileTextIcon
} from "lucide-react";

type ExportData = {
  insightId: string;
  fileName: string;
  metrics: { label: string; value: string | number }[];
  insights: string[];
  recommendations: string[];
  risks: string[];
  opportunities?: string[];
  alerts?: string[];
  executiveSummary?: string;
  domainName?: string;
  generatedAt?: string;
};

function cleanFileBase(name: string): string {
  return name.replace(/\.[^/.]+$/, "").replace(/[^a-zA-Z0-9_-]/g, "_");
}

function downloadBlob(content: string, type: string, fileName: string) {
  const blob = new Blob([content], { type });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = fileName;
  link.click();
}

function formatDate(value?: string) {
  if (!value) return "Just now";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value || "Unknown Date";
  return d.toLocaleString();
}

export function ExportButton({ data }: { data: ExportData }) {
  const [open, setOpen] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);
  const fileBase = useMemo(() => cleanFileBase(data.fileName), [data.fileName]);

  const handleCsvExport = () => {
    setExporting("csv");
    const headers = ["Section", "Item", "Content"];
    const rows: Array<[string, string, string | number]> = [
      ...data.metrics.map((m): [string, string, string | number] => ["Metric", m.label, m.value]),
      ...data.insights.map((i, idx): [string, string, string | number] => ["Insight", `Insight ${idx + 1}`, i]),
      ...data.recommendations.map((r, idx): [string, string, string | number] => ["Recommendation", `Action ${idx + 1}`, r]),
      ...data.risks.map((rk, idx): [string, string, string | number] => ["Risk", `Risk ${idx + 1}`, rk]),
      ...(data.opportunities || []).map((op, idx): [string, string, string | number] => ["Opportunity", `Opportunity ${idx + 1}`, op]),
      ...(data.alerts || []).map((al, idx): [string, string, string | number] => ["Alert", `Alert ${idx + 1}`, al])
    ];

    const csvContent = [
      headers.join(","),
      ...rows.map((e) => e.map((cell) => `"${String(cell).replace(/"/g, "\"\"")}"`).join(","))
    ].join("\n");

    downloadBlob(csvContent, "text/csv;charset=utf-8;", `${fileBase}_insight_report.csv`);
    setTimeout(() => {
      setExporting(null);
      setOpen(false);
    }, 800);
  };

  const handleBriefExport = () => {
    setExporting("brief");
    const markdown = `# Executive Report

**Dataset:** ${data.fileName}
**Domain:** ${data.domainName || "Business Dataset"}
**Generated:** ${formatDate(data.generatedAt)}

## Executive Summary
${data.executiveSummary || "Summary unavailable for this report."}

## Key Metrics
${data.metrics.length ? data.metrics.map((m) => `- **${m.label}:** ${m.value}`).join("\n") : "- No metric snapshots available"}

## Key Insights
${data.insights.length ? data.insights.map((i) => `- ${i}`).join("\n") : "- No key insights"}

## Recommendations
${data.recommendations.length ? data.recommendations.map((r) => `- ${r}`).join("\n") : "- No recommendations"}

## Risks & Alerts
${[...data.risks, ...(data.alerts || [])].length ? [...data.risks, ...(data.alerts || [])].map((r) => `- ${r}`).join("\n") : "- No risks or alerts detected"}

## Opportunities
${(data.opportunities || []).length ? (data.opportunities || []).map((o) => `- ${o}`).join("\n") : "- No explicit opportunities listed"}
`;

    downloadBlob(markdown, "text/markdown;charset=utf-8;", `${fileBase}_executive_brief.md`);
    setTimeout(() => {
      setExporting(null);
      setOpen(false);
    }, 800);
  };

  const handlePptxExport = async () => {
    setExporting("pptx");
    try {
      const pptxgen = (await import("pptxgenjs")).default;
      const pres = new pptxgen();
      pres.author = "AI Data Analyst";
      pres.subject = data.domainName || "Dataset Insight Report";
      pres.title = `Executive Report - ${data.fileName}`;

      const slide1 = pres.addSlide();
      slide1.background = { fill: "0B1220" };
      slide1.addText("EXECUTIVE ANALYSIS REPORT", {
        x: 0.5,
        y: 1.1,
        w: 9,
        h: 0.8,
        fontSize: 28,
        bold: true,
        color: "38BDF8",
        align: "center"
      });
      slide1.addText(data.fileName, {
        x: 0.8,
        y: 2.0,
        w: 8.4,
        h: 0.5,
        fontSize: 16,
        color: "FFFFFF",
        align: "center"
      });
      slide1.addText(data.executiveSummary || "Insight summary generated by AI Data Analyst.", {
        x: 0.8,
        y: 3.0,
        w: 8.4,
        h: 1.5,
        fontSize: 12,
        color: "D1D5DB",
        align: "center"
      });

      if (data.metrics.length > 0) {
        const slideStats = pres.addSlide();
        slideStats.background = { fill: "0F172A" };
        slideStats.addText("KPI Snapshot", {
          x: 0.6,
          y: 0.5,
          color: "22C55E",
          fontSize: 24,
          bold: true
        });
        data.metrics.slice(0, 8).forEach((m, i) => {
          slideStats.addText(`${m.label}: ${m.value}`, {
            x: 0.9,
            y: 1.3 + i * 0.52,
            w: 8.2,
            fontSize: 14,
            color: "E2E8F0",
            bullet: { indent: 10 }
          });
        });
      }

      if (data.insights.length > 0) {
        const slide2 = pres.addSlide();
        slide2.background = { fill: "0F172A" };
        slide2.addText("Strategic Insights", { x: 0.6, y: 0.5, color: "38BDF8", fontSize: 24, bold: true });
        data.insights.slice(0, 6).forEach((insight, i) => {
          slide2.addText(insight, {
            x: 0.8,
            y: 1.2 + i * 0.6,
            w: 8.6,
            fontSize: 13,
            color: "E2E8F0",
            bullet: { indent: 10 }
          });
        });
      }

      if (data.recommendations.length > 0 || data.risks.length > 0) {
        const slide3 = pres.addSlide();
        slide3.background = { fill: "111827" };
        slide3.addText("Action Plan & Risks", { x: 0.6, y: 0.5, color: "F59E0B", fontSize: 24, bold: true });
        slide3.addText("Recommended Actions", { x: 0.8, y: 1.1, color: "10B981", fontSize: 13, bold: true });
        data.recommendations.slice(0, 4).forEach((rec, i) => {
          slide3.addText(rec, {
            x: 1.0,
            y: 1.45 + i * 0.45,
            w: 4.0,
            fontSize: 11,
            color: "D1D5DB",
            bullet: { indent: 8 }
          });
        });
        slide3.addText("Risks / Constraints", { x: 5.1, y: 1.1, color: "EF4444", fontSize: 13, bold: true });
        data.risks.slice(0, 4).forEach((risk, i) => {
          slide3.addText(risk, {
            x: 5.3,
            y: 1.45 + i * 0.45,
            w: 4.0,
            fontSize: 11,
            color: "D1D5DB",
            bullet: { indent: 8 }
          });
        });
      }

      await pres.writeFile({ fileName: `${fileBase}_executive_report.pptx` });
    } catch (err) {
      console.error("PPTX Export Error:", err);
    }

    setExporting(null);
    setOpen(false);
  };

  const handlePdfExport = async () => {
    setExporting("pdf");
    setOpen(false);

    await new Promise((r) => setTimeout(r, 350));

    try {
      const html2canvas = (await import("html2canvas")).default;
      const { jsPDF } = await import("jspdf");

      const element = (document.querySelector(".app-main") || document.querySelector("main") || document.body) as HTMLElement;
      if (!element) throw new Error("Target element not found");

      // Force a light-theme capture mode for the PDF
      document.body.classList.add("is-capturing", "pdf-export-mode");

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false
      });

      const imgData = canvas.toDataURL("image/jpeg", 0.95);
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: [canvas.width / 2, canvas.height / 2]
      });

      pdf.addImage(imgData, "JPEG", 0, 0, canvas.width / 2, canvas.height / 2);
      pdf.save(`${fileBase}_visual_report.pdf`);
    } catch (err) {
      console.error("PDF Export Error:", err);
    } finally {
      document.body.classList.remove("is-capturing", "pdf-export-mode");
      setExporting(null);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        disabled={!!exporting}
        className="primary-btn px-6 py-3 shadow-lg"
        suppressHydrationWarning
      >
        {exporting ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
        {exporting ? "Preparing..." : "Export"}
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-40 bg-black/20 backdrop-blur-sm" onClick={() => setOpen(false)} />
          <div className="absolute right-0 top-full z-50 mt-4 w-72 animate-in fade-in slide-in-from-top-4 rounded-3xl border border-white/10 bg-neutral-900 p-2 shadow-2xl">
            <button
              onClick={handleBriefExport}
              className="flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-medium text-neutral-300 transition-all hover:bg-white/5"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-sky-500/10 text-sky-400">
                {exporting === "brief" ? <Loader2 size={16} className="animate-spin" /> : <FileTextIcon size={16} />}
              </div>
              <div>
                <p className="font-bold text-white">Executive Brief</p>
                <p className="text-[10px] text-neutral-500">Export as Markdown</p>
              </div>
            </button>

            <button
              onClick={handleCsvExport}
              className="mt-1 flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-medium text-neutral-300 transition-all hover:bg-white/5"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-cyan-500/10 text-cyan-400">
                {exporting === "csv" ? <Loader2 size={16} className="animate-spin" /> : <FileCode size={16} />}
              </div>
              <div>
                <p className="font-bold text-white">Structured CSV</p>
                <p className="text-[10px] text-neutral-500">Metrics + insights + actions</p>
              </div>
            </button>

            <button
              onClick={handlePptxExport}
              className="mt-1 flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-medium text-neutral-300 transition-all hover:bg-white/5"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-brand-500/10 text-brand-400">
                {exporting === "pptx" ? <Loader2 size={16} className="animate-spin" /> : <Presentation size={16} />}
              </div>
              <div>
                <p className="font-bold text-white">Executive Slides</p>
                <p className="text-[10px] text-neutral-500">Board-ready PPTX summary</p>
              </div>
            </button>

            <button
              onClick={handlePdfExport}
              className="mt-1 flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-medium text-neutral-300 transition-all hover:bg-white/5"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-red-500/10 text-red-400">
                {exporting === "pdf" ? <Loader2 size={16} className="animate-spin" /> : <FileText size={16} />}
              </div>
              <div>
                <p className="font-bold text-white">Visual PDF Capture</p>
                <p className="text-[10px] text-neutral-500">Snapshot current report page</p>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
